services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpassword
      POSTGRES_DB: autoblog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autoblog-network

  backend:
    image: ghcr.io/garuda-wings/auto-blog-backend:${BACKEND_IMAGE_TAG}
    env_file:
      - ../backend/.env.production
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      REACT_APP_API_BASE: "http://backend:5000" 
    depends_on:
      - db
    networks:
      - autoblog-network

  frontend:
    image: ghcr.io/garuda-wings/auto-blog-frontend:${FRONTEND_IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - autoblog-network

volumes:
  postgres_data:

networks:
  autoblog-network:
    driver: bridge
